lection-1_double-1
js-tasks-ru/htmlcss-20231027_daniilk pull request #5
Opened 2023-11-04 19:56 UTC by crocodileDaniil

1) там же нужно строго задавать размеры кнопок? 
2) и как переопределять переменные в зависимости модификатора, а то в материале, который нашёл, такое ощущение, что не то

2023-11-04 19:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-05 18:35 UTC, GSemikozov requested changes

2023-11-05 18:35 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import url('../../assets/css/main.css');;
ни в коем случае не импортируем глобальные стили в файлы стилей компонентов! наоборот -компоненты подключаем в main.css

2023-11-05 18:35 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons {
это лишних блок / контейнер, не относящийся собственно к блоку .button - удалим

2023-11-05 18:35 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 182px;
ширину кнопки не нужно фиксировать

2023-11-05 18:35 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  flex-shrink: 0;
лишнее

2023-11-05 18:35 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  margin: 32px 20px;
марджины на уровне блока не задаем, и наоборот - нужны внутренние отступы, то есть паддинги

2023-11-05 18:35 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
лучше pointer-events: none

2023-11-05 18:35 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
транзишн общий, поэтом у- на .button.

2023-11-06 15:38 UTC, GSemikozov requested changes

2023-11-06 15:38 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +body {
глобальные или вспомогательные стили в файле стилей компонента не описываем - нужно удалить

2023-11-06 15:38 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  text-align: center;
не хватает паддингов и высоты (или хотя бы паддингов)

2023-11-06 15:38 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px 62px;
паддинги (общие) задаем на уровне блока

2023-11-06 15:38 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  background-color: var(--grey-1);
у этого типа кнопки есть еще border

2023-11-06 20:47 UTC, crocodileDaniil commented on 03-lection1/01-button/button.css
> +body {
учтено

2023-11-06 20:51 UTC, crocodileDaniil commented on 03-lection1/01-button/button.css
> +  text-align: center;
добавляю. Но какие там паддинги по верхним смотреть?

2023-11-06 20:51 UTC, crocodileDaniil commented on 03-lection1/01-button/button.css
> +  padding: 15px 62px;
убрал

2023-11-06 20:54 UTC, crocodileDaniil commented on 03-lection1/01-button/button.css
> +  background-color: var(--grey-1);
паддинги убрал, бордер добавил

2023-11-15 21:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  text-align: center;
`15 15 14`

2023-11-15 21:18 UTC, GSemikozov requested changes

2023-11-15 21:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px;
`15 15 14`
иначе высота не будет 48

2023-11-19 13:22 UTC, crocodileDaniil commented on 03-lection1/01-button/button.css
> +  padding: 15px;
исправил и запушил

2023-11-27 15:34 UTC, GSemikozov approved these changes

2023-11-27 15:34 UTC, merged